# dev
spring:
  profiles:
    active: "dev"
  main:
    allow-bean-definition-overriding: true
  mvc:
    static-path-pattern: /static/**
  servlet:
    multipart:
      location: /tmp
      max-request-size: 10MB
      max-file-size: 10MB
  jpa:
    database-platform: org.hibernate.dialect.Oracle12cDialect
    database: oracle
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    show-sql: true
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    cache: false

datasource:
  oracle:
    driver-class-name: "oracle.jdbc.driver.OracleDriver"
    url: "jdbc:oracle:thin:@st-rds-oracle-conects-book-dev.cqhn8loawgfg.ap-northeast-2.rds.amazonaws.com:1521:LIBRO"
    username:
    password:
    initial-size: 2
    max-active: 10
    max-idle: 5
    min-idle: 2
    max-wait: 3000
    testOnBorrow: true
    testWhileIdle: true
    validation-interval: 20000
    validation-query: SELECT 1 from dual

server:
  port: 8440
  tomcat:
    basedir: ./
    accesslog:
      enabled: true
      pattern: "%{yyyy-MM-dd HH:mm:ss}t %a %s \"%r\" %b (%D ms)"
      directory: log
      suffix: .log
      prefix: access

logging:
  config: classpath:logback-spring-dev.xml
  level:
    org.thymeleaf: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: INFO
    org.quartz.core: INFO
    org.h2.server.web: INFO

upload_file_dir: upload
file_temp_root: /home/unitaslibro/libropartner/tmp/
dangi.url: "https://member.dangi.co.kr"
dangi.cash.url: "http://bill.dangi.co.kr:8080"
skyedu.url: "https://sso.skyedu.com"
libro.join.url: "http://dev-join.libro.co.kr"
conects.url: "https://qa-sapi.conects.com:443"
image.base.path: "/Libro_V6/upload/"
partner.daumshop.put.file.dir: "/home/unitaslibro/libropartner/daumbook/"
partner.naverbook.put.file.dir: "/home/unitaslibro/libropartner/naverbook/"
