#local
spring:
  profiles:
    active: "default"
  main:
    allow-bean-definition-overriding: true
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
    static-path-pattern: /static/**
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    cache: false
  datasource:
    driver-class-name: "oracle.jdbc.driver.OracleDriver"
    #url: "jdbc:oracle:thin:@st-rds-oracle-conects-book-dev.cqhn8loawgfg.ap-northeast-2.rds.amazonaws.com:1521:LIBRO"
    url: "jdbc:oracle:thin:@st-rds-libro.cqhn8loawgfg.ap-northeast-2.rds.amazonaws.com:1521:LIBRO"
    username:
    password:
    initial-size: 2
    max-active: 10
    max-idle: 5
    min-idle: 2
    max-wait: 3000
    testOnBorrow: true
    testWhileIdle: true
    validation-interval: 20000
    validation-query: SELECT 1 from dual


server:
  port: 8440
  tomcat:
    basedir: ./
    accesslog:
      enabled: true
      pattern: "%{yyyy-MM-dd HH:mm:ss}t %a %s \"%r\" %b (%D ms)"
      directory: log
      suffix: .log
      prefix: access


app:
  templates: "src/main/resources/"

logging:
  config: classpath:logback-spring-local.xml
  level:
    org.springframework.web: DEBUG
    org.hibernate: ERROR
servlet:
  multipart:
    location: D:\tmp

upload_file_dir: /Libro_V6/upload/
file_temp_root: D:\tmp\
libro.join.url: "http://dev-join.libro.co.kr"
dangi.url: "https://member.dangi.co.kr"
dangi.cash.url: "http://bill.dangi.co.kr:8080"
skyedu.url: "https://sso.skyedu.com"
conects.url: "https://qa-sapi.conects.com:443"
image.base.path: "/Libro_V6/upload/"
partner.daumshop.put.file.dir: "D:/libro_partner/daum/"
partner.naverbook.put.file.dir: "D:/libro_partner/naverbook/"